# Generated by Django 2.2.4 on 2021-06-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categ',
        ),
        migrations.DeleteModel(
            name='catagory',
        ),
    ]
