# Generated by Django 2.2.4 on 2021-06-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0002_auto_20210604_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='build_pc',
        ),
        migrations.RemoveField(
            model_name='troublshooting',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='status',
        ),
        migrations.DeleteModel(
            name='troublshooting',
        ),
    ]
