# Generated by Django 2.2.4 on 2021-06-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0004_auto_20210604_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('catbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='build_pc_app.catagory')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodtype', to='build_pc_app.brand'),
        ),
    ]
