# Generated by Django 2.2.4 on 2021-06-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0007_auto_20210605_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='thumb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumb',
        ),
    ]
