# Generated by Django 2.2.4 on 2021-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0009_product_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
