# Generated by Django 2.2.4 on 2021-06-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0011_auto_20210605_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='login_reg_app.users'),
        ),
    ]
