# Generated by Django 2.2.4 on 2021-06-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('build_pc_app', '0011_auto_20210605_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='login_reg_app.users'),
        ),
    ]
