# Generated by Django 2.2.4 on 2021-06-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0012_auto_20210605_1100'),
        ('build_pc_app', '0012_order_user_order'),
    ]

    operations = [
    ]
