# Generated by Django 2.2.4 on 2021-06-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_pc_app', '0016_auto_20210606_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.DeleteModel(
            name='troublshooting',
        ),
    ]
